<?php
/**
 * Plugin Data Structure
 *
 * @package    WordPress
 * @subpackage Multiple Products to Cart for WooCommerce
 * @since      3.0
 */

defined( 'ABSPATH' ) || exit;

global $mpc__;

$mpc__           = array(
	'has_pro'       => false,
	'prostate'      => 'none',
	'prolink'       => 'https://webfixlab.com/plugins/multiple-products-to-cart-woocommerce-product-table/',
	'activate_link' => 'admin.php?page=mpc-shortcodes-pricing',
	'plugin'        => array(
		'page_limit'      => 10,
		'screen'          => array(
			'toplevel_page_mpc-shortcodes',
			'multiple-products_page_mpc-shortcode',
			'multiple-products_page_mpc-settings',
			'multiple-products_page_mpca_license',
		),
		'review_link'     => 'https://wordpress.org/support/plugin/multiple-products-to-cart-for-woocommerce/reviews/?rate=5#new-post',
		'support'         => 'https://webfixlab.com/contact/',
		'request_quote'   => 'https://webfixlab.com/contact/',
		'woo_url'         => 'https://wordpress.org/plugins/woocommerce/',
		'free_mpc_url'    => 'https://wordpress.org/plugins/multiple-products-to-cart-for-woocommerce/',
		'notice_interval' => 15, // days.
	),
	'notice'        => array(),
);
$mpc__['fields'] = array(
	'general-settings' => array(
		array(
			'section' => __( 'Redirect & Quantity', 'multiple-products-to-cart-for-woocommerce' ),
			'desc'    => '',
			'fields'  => array(
				array(
					'key'              => 'wmc_redirect',
					'type'             => 'radio',
					'options'          => array(
						'ajax'   => __( 'None', 'multiple-products-to-cart-for-woocommerce' ),
						'cart'   => __( 'Cart', 'multiple-products-to-cart-for-woocommerce' ),
						'custom' => __( 'Custom', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'default'          => 'ajax',
					'label'            => __( 'Redirect After Cart Addition', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'             => __( 'Choose the page to redirect customers to after they\'ve added products to their cart.', 'multiple-products-to-cart-for-woocommerce' ),
					'followup'         => array(
						array(
							'key'         => 'mpca_custom_redirect',
							'type'        => 'text',
							'label'       => __( 'Custom Page URL', 'multiple-products-to-cart-for-woocommerce' ),
							'placeholder' => 'https://webfixlab.com/contact/',
							'desc'        => __( 'Add a custom page URL where the customer should be redirected.', 'multiple-products-to-cart-for-woocommerce' ),
						),
					),
					'followup_depends' => 'custom',
					'pro_label'        => __( 'Custom Redirect URL', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'wmca_default_quantity',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Initial Product Quantity', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Set the starting value for the quantity field for each product.', 'multiple-products-to-cart-for-woocommerce' ),
					'placeholder' => '0',
					'class'       => 'number-input',
				),
				array(
					'key'         => 'mpc_show_new_quantity_box',
					'type'        => 'checkbox',
					'label'       => __( 'Quantity Selector Design', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Decide whether the quantity field should incorporate a plus-minus selector style.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'pro'         => true,
				),
			),
		),
		array(
			'section' => __( 'Buttons', 'multiple-products-to-cart-for-woocommerce' ),
			'desc'    => '',
			'fields'  => array(
				array(
					'key'         => 'wmca_show_reset_btn',
					'type'        => 'checkbox',
					'label'       => __( 'Reset Button', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Choose if a Reset button should accompany the Add to Cart button.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
				),
				array(
					'key'         => 'wmc_show_all_select',
					'type'        => 'checkbox',
					'label'       => __( 'Select All', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Choose if a \'Select All\' checkbox should be added at the top right corner of the product table.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
				),
				array(
					'key'         => 'mpc_show_add_to_cart_button',
					'type'        => 'checkbox',
					'label'       => __( 'Add to Cart Button', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Choose if you want to remove the Add to Cart button.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_add_to_cart_checkbox',
					'type'        => 'checkbox',
					'label'       => __( 'Checkbox', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Choose if you want to remove the checkboxes from the product table, assuming customers will purchase all products from the current page of the product table.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'pro'         => true,
				),
				array(
					'key'         => 'wmca_single_cart',
					'type'        => 'checkbox',
					'label'       => __( 'Individual \'Add to Cart\' Button', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Decide if each product should have its own \'Add to Cart\' button.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'pro'         => true,
				),
			),
		),
		array(
			'section' => __( 'Search & Filter', 'multiple-products-to-cart-for-woocommerce' ),
			'desc'    => '',
			'fields'  => array(
				array(
					'key'         => 'wmc_show_products_filter',
					'type'        => 'checkbox',
					'label'       => __( 'Product Sorting Dropdown', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Choose if a product sorting dropdown should be displayed at the top of the product table.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
				),
				array(
					'key'         => 'mpc_show_title_dopdown',
					'type'        => 'checkbox',
					'label'       => __( 'Title Sorting Option', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Choose if a \'Title\' option should be included in the sorting dropdown.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
				),
				array(
					'key'         => 'wmca_allow_sku_sort',
					'type'        => 'checkbox',
					'label'       => __( 'SKU Sorting Option', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Choose if an \'SKU\' option should be included in the sorting dropdown.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_show_ajax_search',
					'type'        => 'checkbox',
					'label'       => __( 'Enable Ajax Search Box', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Choose if an Ajax-powered search box should be added to the product table.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_show_ajax_cat_filter',
					'type'        => 'checkbox',
					'label'       => __( 'Category Filter Dropdown', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Choose if a Category Filter dropdown should be displayed on the product table.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_show_ajax_tag_filter',
					'type'        => 'checkbox',
					'label'       => __( 'Tags Filter Dropdown', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Choose if a Tags Filter dropdown should be displayed on the product table.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_show_cat_counter',
					'type'        => 'checkbox',
					'label'       => __( 'Show Product Count per Category', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Displays products count per category or not. Please note: for sites with more than 800 products, dynamic products count is OFF. For smaller sites it will dynamically count products specific to the table.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'pro'         => true,
				),
			),
		),
		array(
			'section' => __( 'Others', 'multiple-products-to-cart-for-woocommerce' ),
			'desc'    => '',
			'fields'  => array(
				array(
					'key'         => 'mpc_show_cart',
					'type'        => 'checkbox',
					'label'       => __( 'Display cart after table', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Choose if you want to display cart at the bottom of the table(s).', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'pro'         => true,
				),
				array(
					'key'         => 'wmc_show_pagination_text',
					'type'        => 'checkbox',
					'label'       => __( 'Display Pagination Text', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Choose whether or not to display text like "Showing Products 1 - 10 / 75" above the pagination.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
				),
				array(
					'key'         => 'mpc_show_product_gallery',
					'type'        => 'checkbox',
					'label'       => __( 'Product Image Gallery', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Choose to include additional product gallery images under the featured image in the product table.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_show_stock_out',
					'type'        => 'checkbox',
					'label'       => __( 'Display Out-of-Stock Products', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Choose to include out-of-stock products in the table. Note: products must be allowed to backorder.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_show_subscription',
					'type'        => 'checkbox',
					'label'       => __( 'Support Subscription Products', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Enable subscription product types.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'pro'         => true,
				),
				array(
					'key'         => 'wmca_show_header',
					'type'        => 'checkbox',
					'label'       => __( 'Table Header', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Choose whether to hide or display the table headers, which include the column titles.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_show_total_price',
					'type'        => 'checkbox',
					'label'       => __( 'Total Price', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Hide or show table total price', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_show_category_subheader',
					'type'        => 'checkbox',
					'label'       => __( 'Section by Categories', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'There must be selected categories in the table to enable this feature.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_show_on_sale',
					'type'        => 'checkbox',
					'label'       => __( 'Show \'Sale\' Label', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Choose whether to add a \'Sale\' sticker to the featured product image.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
				),
			),
		),
	),
	'labels'           => array(
		array(
			'section' => __( 'Buttons', 'multiple-products-to-cart-for-woocommerce' ),
			'desc'    => '',
			'fields'  => array(
				array(
					'key'         => 'wmc_button_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Add to Cart', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Add to Cart', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'mpce_single_order_button_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Single Add to Cart', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Add', 'multiple-products-to-cart-for-woocommerce' ),
					'pro'         => true,
				),
			),
		),
		array(
			'section' => __( 'Table Column Titles', 'multiple-products-to-cart-for-woocommerce' ),
			'desc'    => '',
			'fields'  => array(
				array(
					'key'         => 'wmc_ct_image',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Image', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Image', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'wmc_ct_product',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Product', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Product', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'wmc_ct_price',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Price', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Price', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'wmc_ct_variation',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Variation', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Variation', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'wmc_ct_quantity',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Quantity', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Quantity', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'wmc_ct_buy',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Buy', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Buy', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'wmc_ct_category',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Category', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Category', 'multiple-products-to-cart-for-woocommerce' ),
					'pro'         => true,
				),
				array(
					'key'         => 'wmc_ct_stock',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Stock', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Stock', 'multiple-products-to-cart-for-woocommerce' ),
					'pro'         => true,
				),
				array(
					'key'         => 'wmc_ct_tag',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Tag', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Tag', 'multiple-products-to-cart-for-woocommerce' ),
					'pro'         => true,
				),
				array(
					'key'         => 'wmc_ct_sku',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'SKU', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'SKU', 'multiple-products-to-cart-for-woocommerce' ),
					'pro'         => true,
				),
				array(
					'key'         => 'wmc_ct_rating',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Rating', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Rating', 'multiple-products-to-cart-for-woocommerce' ),
					'pro'         => true,
				),
			),
		),
		array(
			'section' => __( 'Sorting Option', 'multiple-products-to-cart-for-woocommerce' ),
			'desc'    => '',
			'fields'  => array(
				array(
					'key'         => 'mpc_sddt_default',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Default sorting', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Default sorting', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'mpc_sddt_price_asc',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Price: Low to High', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Price: Low to High', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'mpc_sddt_price_desc',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Price: High to Low', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Price: High to Low', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'mpc_sddt_title_asc',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Title: A to Z', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Title: A to Z', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'mpc_sddt_title_desc',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Title: Z to A', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Title: Z to A', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'mpc_sddt_sku_asc',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'SKU: A to Z', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'SKU: A to Z', 'multiple-products-to-cart-for-woocommerce' ),
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_sddt_sku_dessc',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'SKU: Z to A', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'SKU: Z to A', 'multiple-products-to-cart-for-woocommerce' ),
					'pro'         => true,
				),
			),
		),
		array(
			'section' => __( 'Others', 'multiple-products-to-cart-for-woocommerce' ),
			'desc'    => '',
			'fields'  => array(
				array(
					'key'         => 'wmc_total_button_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Total', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Total', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'wmc_pagination_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Pagination', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( '', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'wmc_select_all_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Selelct All', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Selelct All', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'wmc_empty_value_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Empty Value', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'N/A', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'wmc_option_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Prepend Placeholder Variation', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Default: Blank. Example: {Choose} Variation', 'multiple-products-to-cart-for-woocommerce' ),
				),
			),
		),
		array(
			'section' => __( 'Error Notice', 'multiple-products-to-cart-for-woocommerce' ),
			'desc'    => '',
			'fields'  => array(
				array(
					'key'         => 'wmc_empty_form_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Product Not Selected', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Please check one or more products', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'wmc_missed_variation_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Variation Not Selected', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Please select all options', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'mpcp_empty_result_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => __( 'Empty Search Result', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => __( 'Sorry! No products found.', 'multiple-products-to-cart-for-woocommerce' ),
					'pro'         => true,
				),
			),
		),
	),
	'appearence'       => array(
		array(
			'section' => __( 'Images', 'multiple-products-to-cart-for-woocommerce' ),
			'desc'    => '',
			'fields'  => array(
				array(
					'key'         => 'mpc_image_size',
					'type'        => 'number',
					'default'     => '',
					'label'       => __( 'Product Image Size (px)', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => '72',
					'min'         => 50,
					'max'         => 152,
					'class'       => 'number-input',
				),
			),
		),
		array(
			'section' => __( 'Product Title', 'multiple-products-to-cart-for-woocommerce' ),
			'desc'    => '',
			'fields'  => array(
				array(
					'key'     => 'mpc_protitle_color',
					'type'    => 'color',
					'default' => '',
					'label'   => __( 'Color', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'    => '',
				),
				array(
					'key'         => 'mpc_protitle_bold_font',
					'type'        => 'checkbox',
					'label'       => __( 'Bold', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'pro_label'   => __( 'Product Title Bold Font', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'mpc_protitle_underline',
					'type'        => 'checkbox',
					'label'       => __( 'Underline', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'pro_label'   => __( 'Product Title Underline', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'mpc_protitle_font_size',
					'type'        => 'number',
					'default'     => '',
					'label'       => __( 'Font Size (px)', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => '',
					'placeholder' => '10',
					'min'         => 10,
					'max'         => 50,
					'class'       => 'number-input',
					'pro_label'   => __( 'Product Title Font Size', 'multiple-products-to-cart-for-woocommerce' ),
				),
			),
		),
		array(
			'section' => __( 'Add to Cart Button', 'multiple-products-to-cart-for-woocommerce' ),
			'desc'    => '',
			'fields'  => array(
				array(
					'key'     => 'mpc_button_text_color',
					'type'    => 'color',
					'default' => '',
					'label'   => __( 'Text', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'    => '',
				),
				array(
					'key'     => 'wmc_button_color',
					'type'    => 'color',
					'default' => '',
					'label'   => __( 'Background', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'    => '',
				),
			),
		),
		array(
			'section' => __( 'Header and Pagination', 'multiple-products-to-cart-for-woocommerce' ),
			'desc'    => '',
			'fields'  => array(
				array(
					'key'     => 'mpc_head_text_color',
					'type'    => 'color',
					'default' => '',
					'label'   => __( 'Text', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'    => '',
				),
				array(
					'key'     => 'wmc_thead_back_color',
					'type'    => 'color',
					'default' => '',
					'label'   => __( 'Background', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'    => '',
				),
			),
		),
	),
	'new_table'        => array(
		array(
			'section' => __( 'Add New Product Table', 'multiple-products-to-cart-for-woocommerce' ),
			'desc'    => '',
			'fields'  => array(
				array(
					'key'         => 'shortcode_title',
					'type'        => 'text',
					'label'       => __( 'Table Title', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'For internal use only, it helps admins identify the table and will not be shown to customers.', 'multiple-products-to-cart-for-woocommerce' ),
					'placeholder' => __( 'Product table title', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'         => 'shortcode_desc',
					'type'        => 'text',
					'label'       => __( 'Table Description', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'For internal use only, it helps admins identify the table and will not be shown to customers.', 'multiple-products-to-cart-for-woocommerce' ),
					'placeholder' => __( 'Description', 'multiple-products-to-cart-for-woocommerce' ),
				),
				array(
					'key'          => 'ids',
					'type'         => 'selectbox',
					'label'        => __( 'Add Product', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'         => __( 'Select specific products to display if you want to add only certain items in the product table.', 'multiple-products-to-cart-for-woocommerce' ),
					'content_type' => 'product',
					'multiple'     => true,
				),
				array(
					'key'          => 'selected',
					'type'         => 'selectbox',
					'label'        => __( 'Selected Products', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'         => __( 'Choose which products should be checked by default when the product table initially loads.', 'multiple-products-to-cart-for-woocommerce' ),
					'content_type' => 'product',
					'multiple'     => true,
				),
				array(
					'key'          => 'skip_products',
					'type'         => 'selectbox',
					'label'        => __( 'Skip Products', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'         => __( 'Choose which products should be skipped by default when the product table initially loads.', 'multiple-products-to-cart-for-woocommerce' ),
					'content_type' => 'product',
					'multiple'     => true,
				),
				array(
					'key'          => 'cats',
					'type'         => 'selectbox',
					'label'        => __( 'Categories', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'         => __( 'Specify the product categories to be included in the product table.', 'multiple-products-to-cart-for-woocommerce' ),
					'content_type' => 'product_cat',
					'multiple'     => true,
				),
				array(
					'key'         => 'limit',
					'type'        => 'text',
					'label'       => __( 'Products Per Page', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => sprintf(
						// translators: %1$s: openning strong tag with css, %2$s: closing strong tag.
						__( 'Set a limit on the number of products to display per page. This option is functional only when the Pagination setting is Show. Maximum page limit is %1$s100.%2$s', 'multiple-products-to-cart-for-woocommerce' ),
						'<strong style="font-weight:bold;">',
						'</strong>'
					),
					'placeholder' => 10,
					'min'         => 1,
					'max'         => 50,
				),
				array(
					'key'         => 'pagination',
					'type'        => 'checkbox',
					'label'       => __( 'Pagination', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'If Hide is selected, all products will be shown on a single page without pagination.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'default'     => 'on',
				),
				array(
					'key'          => 'orderby',
					'type'         => 'selectbox',
					'label'        => __( 'Order By', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'         => __( 'Determine the attribute (like price, name, etc.) upon which the product sorting should be based.', 'multiple-products-to-cart-for-woocommerce' ),
					'options'      => array(
						'date'  => __( 'Date', 'multiple-products-to-cart-for-woocommerce' ),
						'title' => __( 'Title', 'multiple-products-to-cart-for-woocommerce' ),
						'price' => __( 'Price', 'multiple-products-to-cart-for-woocommerce' ),
						'id'    => __( 'ID', 'multiple-products-to-cart-for-woocommerce' ),
						'sku'   => __( 'SKU', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'default'      => 'date',
					'content_type' => 'static',
					'multiple'     => false,
					'pro_options'  => array( 'id', 'sku' ),
				),
				array(
					'key'          => 'order',
					'type'         => 'selectbox',
					'label'        => __( 'Order', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'         => __( 'Define the display sequence as ascending, descending, or custom. The custom setting is functional only when you have pre-selected specific products in the Add Product section.', 'multiple-products-to-cart-for-woocommerce' ),
					'options'      => array(
						'desc'   => __( 'DESC', 'multiple-products-to-cart-for-woocommerce' ),
						'asc'    => __( 'ASC', 'multiple-products-to-cart-for-woocommerce' ),
						'custom' => __( 'Custom', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'default'      => 'desc',
					'content_type' => 'static',
					'multiple'     => false,
					'pro_options'  => array( 'custom' ),
				),
				array(
					'key'         => 'description',
					'type'        => 'checkbox',
					'label'       => __( 'Product Description', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'This is the individual product description.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'default'     => 'off',
				),
				array(
					'key'         => 'link',
					'type'        => 'checkbox',
					'label'       => __( 'Product Link', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'        => __( 'Choose whether or not product titles should link to their individual product pages.', 'multiple-products-to-cart-for-woocommerce' ),
					'switch_text' => array(
						'on'  => __( 'Show', 'multiple-products-to-cart-for-woocommerce' ),
						'off' => __( 'Hide', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'default'     => 'on',
				),
				array(
					'key'          => 'type',
					'type'         => 'selectbox',
					'label'        => __( 'Product Type', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'         => __( 'Select the types of products you wish to include in the product table.', 'multiple-products-to-cart-for-woocommerce' ),
					'options'      => array(
						'all'                   => __( 'All', 'multiple-products-to-cart-for-woocommerce' ),
						'simple'                => __( 'Simple', 'multiple-products-to-cart-for-woocommerce' ),
						'variable'              => __( 'Variable', 'multiple-products-to-cart-for-woocommerce' ),
						'grouped'               => __( 'Grouped', 'multiple-products-to-cart-for-woocommerce' ),
						'subscription'          => __( 'Subscription', 'multiple-products-to-cart-for-woocommerce' ),
						'variable-subscription' => __( 'Variable Subscription', 'multiple-products-to-cart-for-woocommerce' ),
					),
					'default'      => 'all',
					'content_type' => 'static',
					'multiple'     => true,
					'pro_options'  => array( 'grouped', 'subscription', 'variable-subscription' ),
				),
				array(
					'key'     => 'columns',
					'type'    => 'sortable',
					'label'   => __( 'Columns', 'multiple-products-to-cart-for-woocommerce' ),
					'desc'    => __( 'Set table columns (like name, category etc). NOTE: <strong>variation</strong> is a must have column.', 'multiple-products-to-cart-for-woocommerce' ),
					'default' => '',
				),
			),
		),
	),
);

// hook to modify global $mpc__ data variable.
do_action( 'mpca_modify_core_data' );
